<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EN32276" name="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest" tests="6" failures="0" timestamp="08 Nov 2017 19:10:15 GMT" time="0.011" errors="0">
  <testcase name="OkThenKoWorks" time="0.001" classname="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest"/>
  <testcase name="OkThenOkWorks" time="0.003" classname="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest"/>
  <testcase name="exceptionOnFirstProcessingWorks" time="0.002" classname="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest"/>
  <testcase name="keywordExists" time="0.002" classname="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest"/>
  <testcase name="KoThenKoWorks" time="0.001" classname="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest"/>
  <testcase name="exceptionOnSecondProcessingWorks" time="0.002" classname="com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest"/>
</testsuite> <!-- com.github.fge.jsonschema.keyword.validator.callback.draftv4.AnyOfValidatorTest -->
